# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_per_day', models.IntegerField(default=1)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
